//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proje1Entities : DbContext
    {
        public proje1Entities()
            : base("name=proje1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akademik_Ders> Akademik_Ders { get; set; }
        public virtual DbSet<Akademik_Ders_Öğrenci> Akademik_Ders_Öğrenci { get; set; }
        public virtual DbSet<Akademik_Dönem> Akademik_Dönem { get; set; }
        public virtual DbSet<Danışman> Danışman { get; set; }
        public virtual DbSet<Ders_Ekleme_Çıkarma> Ders_Ekleme_Çıkarma { get; set; }
        public virtual DbSet<Kullanıcı> Kullanıcı { get; set; }
        public virtual DbSet<Öğrenci> Öğrenci { get; set; }
        public virtual DbSet<Uzmanlık_Alanı> Uzmanlık_Alanı { get; set; }
        public virtual DbSet<Yorum> Yorum { get; set; }
    }
}
